---
title: "Writing scrape data to MySQL on AWS"
author: "Jack Wright"
date: "10/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


AWS Connection


```{r setup_2, echo=TRUE}
library(DBI)
library(tidyverse)

library(nycflights13)  # to bring in airlines table

```

## Setup MySQL database connection 

Obtain login credentials for database connection.

```{r setup_DBcon, echo=TRUE}
#prompt for input 

password_file<-"C:\\password-files-for-r\\AWS_login.csv"

passwords<-read.csv(password_file)
# read in login credentials
df_login <- passwords   # read in login credentials

vardb_user <- df_login$login_name
vardb_password <- df_login$login_password
vardb_schema <- df_login$login_schema
vardb_host <- df_login$login_host

#cat("Host: ", vardb_host, " Schema=", vardb_schema, " username=", vardb_user, " password=", vardb_password)


mydb = dbConnect(RMySQL::MySQL(), user=vardb_user,  password=vardb_password, port=3306, dbname=vardb_schema, host=vardb_host)

```

## getting file encoding correct

There is a problem with the encoding of the "description column" when you try to upload it directly, so you need to export it, then reimport it.

```{r}

write.table(ny_data_scrape,file="tmp.txt", fileEncoding ="utf8")
mydata_utf8 <- read.table(file="tmp.txt",encoding="utf8") 

```


## upload table to the cloud

```{r}

written_df<-dbWriteTable(mydb,"nyc_data_scrape",
                         mydata_utf8,append=TRUE,row.names=FALSE)

```


## check if table is up

```{r}

dbListTables(mydb)

```

